version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: risk_mirror
    volumes:
      - mongodb_data:/data/db
    networks:
      - risk_mirror_net

networks:
  risk_mirror_net:
    driver: bridge

volumes:
  mongodb_data: 
